### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by MJarvan** [MJarvan/the-light-of-gdufe-app#4]
[Product Backlog](http://share.weiyun.com/59bb7ff0bf31d15fc29fc4bef4f29fcc)

**Comment by ch666** [comment]
well done

**Comment by maicheng** [comment]
yoyo切克闹

**Comment by maicheng** [comment]
hello,Do you love me?

**Comment by taoge525** [comment]
https://github.com/fariashen/campus-express/wiki
